# Generated by Django 4.2.11 on 2024-05-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customuser_bio_customuser_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_to', models.IntegerField(choices=[(0, 'Language'), (1, 'Framework'), (2, 'Library'), (3, 'Other')])),
            ],
        ),
    ]
