# Generated by Django 4.2.11 on 2024-05-03 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_relatedto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('topic_related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.relatedto')),
            ],
        ),
    ]
