# Generated by Django 4.2.11 on 2024-05-04 14:44

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default=base.models.CustomUser.random_image, null=True, upload_to=''),
        ),
    ]
