# Generated by Django 4.2.11 on 2024-05-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_othertopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameworks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.framework')),
                ('languages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.language')),
                ('librarys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.library')),
                ('other_topics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.othertopic')),
            ],
        ),
    ]
